naryCmp: nary.o naryDr.o que.o iter.o nary.h
	gcc nary.o naryDr.o que.o iter.o -o nProg

nary.o: nary.c nary.h
	gcc -c nary.c

naryDr.o: naryDr.c nary.h
	gcc -c naryDr.c

que.o: que.c que.h
	gcc -c que.c

iter.o: iter.c iter.h
	gcc -c iter.c
